config/routes.rb
Rails.application.routes.draw do
  root to: 'cocktails#index'

  resources :cocktails do
    resources :doses, only: [:new, :create]
  end
  resources :doses, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, presence: true, uniqueness: true
  validates :photo, presence: true
  has_one_attached :photo
end

app/models/dose.rb
class Dose < ApplicationRecord
  validates :description, presence: true
  validates :cocktail, presence: true, uniqueness: { scope: :ingredient }
  belongs_to :ingredient
  belongs_to :cocktail
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :doses
  has_many :cocktails, through: :doses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    @dose = Dose.new
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)

    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def edit
    @cocktail = Cocktail.find(params[:id])
  end

  def update
    @cocktail = Cocktail.find(params[:id])
    @cocktail.update(cocktail_params)
    redirect_to cocktail_path(@cocktail)
  end

  def destroy
    @cocktail = Cocktail.find(params[:id])
    @cocktail.destroy
    redirect_to cocktails_path(@cocktail)
  end

private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail

    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/_form.html.erb
<div class="container">

<%= simple_form_for(@cocktail) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name, placeholder: "Cuba Libre" %>
    <%= f.input :photo, as: :file %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn-grad' %>
  </div>
<% end %>
</div>

app/views/cocktails/edit.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= cl_image_path @cocktail.photo.key, width: 400, height: 500, crop: :fill %>')">
  <div class="container">
    <h1>EMBUSCADE.</h1>
    <h2>Okay. Mais juste un verre.</h2>
  </div>
</div>

<div class="container">
  <h3>Edit this cocktail cocktail</h3>

  <%= render 'form', cocktail: @cocktail %>

  <%= link_to 'Back', cocktails_path, class: 'btn btn-light' %>
</div>

<div class="footer">
Made with🍸 at Lille.
</div>

app/views/cocktails/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://source.unsplash.com/featured/?cocktail)">
  <div class="container">
    <h1>EMBUSCADE.</h1>
    <h2>Okay. Mais juste un verre.</h2>
  </div>
</div>

<div class="container">
<%= link_to 'Une recette secrète ?', new_cocktail_path(@cocktail), class: "btn-grad" %>

  <div class="cards">
    <% @cocktails.each do |cocktail| %>
      <%= link_to cocktail_path(cocktail) do %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path cocktail.photo.key, width: 400, height: 500, crop: :fill %>')"><%= cocktail.name %></div>
      <% end %>
    <% end %>
  </div>
</div>

<div class="footer">
Made with🍸 at Lille.
</div>

app/views/cocktails/new.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://source.unsplash.com/featured/?cocktail)">
  <div class="container">
    <h1>EMBUSCADE.</h1>
    <h2>Okay. Mais juste un verre.</h2>
  </div>
</div>

<div class="container">
  <h3>Add a new cocktail</h3>

  <%= render 'form', cocktail: @cocktail %>

  <%= link_to 'Back', cocktails_path, class: 'btn btn-light' %>
</div>

<div class="footer">
Made with🍸 at Lille.
</div>

app/views/cocktails/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= cl_image_path @cocktail.photo.key, width: 400, height: 500, crop: :fill %>')">
  <div class="container">
    <h1><%= @cocktail.name %></h1>
    <h2>Une valeur sûre.</h2>
  </div>
</div>

<div class="container">
  <h3>Ingrédients</h3>
  <div class="ingredients">
  <ul>
    <% @cocktail.doses.each do |dose| %>
      <li><%= dose.ingredient.name %> — <%= dose.description %>
        <%= link_to cocktail_path(@cocktail), method: :delete, data: { confirm: "Are you sure?" } do %>
        <i class="fa fa-trash destroy_dose"></i>
        <% end %>
      </li>
    <% end %>
  </ul>
  <%= link_to 'Add a new ingredient', new_cocktail_dose_path(@cocktail), class: 'btn-grad' %><br><br>
  <%= link_to 'Edit this cocktail', edit_cocktail_path(@cocktail), class: 'btn btn-light' %>
  <%= link_to 'Delete this cocktail', cocktail_path(@cocktail), class: 'btn btn-light', method: :delete %>
  <%= link_to 'Back', cocktails_path, style: "text-decoration: none", class: 'btn-flat' %>
  </div>
</div>

<div class="footer">
Made with🍸 at Lille.
</div>
</body>

app/views/doses/new.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= cl_image_path @cocktail.photo.key, width: 400, height: 500, crop: :fill %>')">
  <div class="container">
    <h1><%= @cocktail.name %></h1>
    <h2>Une valeur sûre.</h2>
  </div>
</div>

<div class="container">
  <h3>Add a new ingredient</h3>

  <%= simple_form_for [@cocktail, @dose] do |f| %>
    <%= f.association :ingredient, collection: Ingredient.order(:name), prompt: "Choose an ingredient" %>
    <%= f.input :description %>
    <%= f.submit "Add an ingredient", class: 'btn btn-light' %>
  <% end %>
<br>
  <%= link_to 'Back', cocktail_path(@cocktail), style: "text-decoration: none", class: 'btn-flat' %>
</div>

<div class="footer">
Made with🍸 at Lille.
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <style>
    @import url('https://fonts.googleapis.com/css2?family=Righteous&display=swap');
    @import url('https://fonts.googleapis.com/css2?family=Montserrat:wght@300;500;700&display=swap');
    </style>
  </head>

  <body>
    <%= yield %>
  </body>
</html>